name: PulseEvents
version: 0.0.2
main: com.voidpulse.pulseevents.PulseEvents
api-version: 1.20

commands:
  pe:
    description: Main command
    usage: /pe <help|start|stop|status|reload|update>
    permission: pulseevents.admin

permissions:
  pulseevents.admin:
    description: Access to admin features
    default: op
